// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZEfrcSikPVarTBFKEn9ufJ5Mqgdk5jo',
    appId: '1:601940301010:web:b593fee3635d687f82890b',
    messagingSenderId: '601940301010',
    projectId: 'freelance-college',
    authDomain: 'freelance-college.firebaseapp.com',
    storageBucket: 'freelance-college.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBonLNwYbx3eMrRdoaRjTAxO35oDaW6NJA',
    appId: '1:601940301010:android:2de5ed113c9734c382890b',
    messagingSenderId: '601940301010',
    projectId: 'freelance-college',
    storageBucket: 'freelance-college.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIkhNdn8fkQYmJ6xhFhBFZztac78AVRPo',
    appId: '1:601940301010:ios:0acf621ef8aee77682890b',
    messagingSenderId: '601940301010',
    projectId: 'freelance-college',
    storageBucket: 'freelance-college.appspot.com',
    iosBundleId: 'com.example.uiForCollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIkhNdn8fkQYmJ6xhFhBFZztac78AVRPo',
    appId: '1:601940301010:ios:0acf621ef8aee77682890b',
    messagingSenderId: '601940301010',
    projectId: 'freelance-college',
    storageBucket: 'freelance-college.appspot.com',
    iosBundleId: 'com.example.uiForCollege',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCZEfrcSikPVarTBFKEn9ufJ5Mqgdk5jo',
    appId: '1:601940301010:web:bd640b629f7d8e8782890b',
    messagingSenderId: '601940301010',
    projectId: 'freelance-college',
    authDomain: 'freelance-college.firebaseapp.com',
    storageBucket: 'freelance-college.appspot.com',
  );

}