// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ntG4wztOSaKzpqC6T7tKGbSb3mMmG3E',
    appId: '1:988669398352:web:a9d28f7a7bb75ba81b3055',
    messagingSenderId: '988669398352',
    projectId: 'majlisproject-673df',
    authDomain: 'majlisproject-673df.firebaseapp.com',
    storageBucket: 'majlisproject-673df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2FaCHih9JLR46QLVhNOfYiHjA-dL9Dbg',
    appId: '1:988669398352:android:b109076f1e9b04431b3055',
    messagingSenderId: '988669398352',
    projectId: 'majlisproject-673df',
    storageBucket: 'majlisproject-673df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzKKHRMSitlFHyqkesZvG4145vtwfh4A',
    appId: '1:988669398352:ios:06988c9df292360b1b3055',
    messagingSenderId: '988669398352',
    projectId: 'majlisproject-673df',
    storageBucket: 'majlisproject-673df.appspot.com',
    iosBundleId: 'com.example.uiForCollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzKKHRMSitlFHyqkesZvG4145vtwfh4A',
    appId: '1:988669398352:ios:06988c9df292360b1b3055',
    messagingSenderId: '988669398352',
    projectId: 'majlisproject-673df',
    storageBucket: 'majlisproject-673df.appspot.com',
    iosBundleId: 'com.example.uiForCollege',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8ntG4wztOSaKzpqC6T7tKGbSb3mMmG3E',
    appId: '1:988669398352:web:c4653578361a65881b3055',
    messagingSenderId: '988669398352',
    projectId: 'majlisproject-673df',
    authDomain: 'majlisproject-673df.firebaseapp.com',
    storageBucket: 'majlisproject-673df.appspot.com',
  );
}
