// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvdYDBT96Xr_gpKLbgQgJRO3sZfxk1kRI',
    appId: '1:866083465276:web:24d1cbfef00699e952fb39',
    messagingSenderId: '866083465276',
    projectId: 'finalproject-ad87d',
    authDomain: 'finalproject-ad87d.firebaseapp.com',
    storageBucket: 'finalproject-ad87d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn67dGkj7mlfUGh7EB0SAz-S1qqXNM3Jk',
    appId: '1:866083465276:android:3237bcb8fb4e885752fb39',
    messagingSenderId: '866083465276',
    projectId: 'finalproject-ad87d',
    storageBucket: 'finalproject-ad87d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5x2jQ319z_ARCRICydaBw9IE9riGwc5w',
    appId: '1:866083465276:ios:07e8a7b095d9f4d652fb39',
    messagingSenderId: '866083465276',
    projectId: 'finalproject-ad87d',
    storageBucket: 'finalproject-ad87d.appspot.com',
    iosBundleId: 'com.example.uiForCollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5x2jQ319z_ARCRICydaBw9IE9riGwc5w',
    appId: '1:866083465276:ios:c34f044aa9ab247d52fb39',
    messagingSenderId: '866083465276',
    projectId: 'finalproject-ad87d',
    storageBucket: 'finalproject-ad87d.appspot.com',
    iosBundleId: 'com.example.uiForCollege.RunnerTests',
  );
}
